INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES(10001, 'USD', 'EUR', 0.85, '');
INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES(10002, 'USD', 'RON', 4.18, '');
INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES(10003, 'USD', 'GBP', 0.72, '');
INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES(10004, 'USD', 'JPY', 110.5, '');
INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT)
VALUES(10005, 'USD', 'CAD', 1.25, '');